wandb_project: qfl-playground
data_path: "data-tiny/"
dataset: "MRI"
seed: 0
num_workers: 0
max_epochs: 10
batch_size: 10
splitter: 10
device: "gpu"
number_clients: 1
export_results_path: "results/"
matrix_export: True
roc_export: True
min_fit_clients: 1
min_avail_clients: 1
min_eval_clients: 1
rounds: 3
frac_fit: 1.0
frac_eval: 0.5
lr: 1e-3
private_key_path: "private_key.pkl"  # private key of client
public_key_path: "public_key.pkl"  # publc key of client
model_checkpoint_path: "model_checkpoint.pt" # used to store unencrypted checkpoints
encrypted_model_checkpoint_path: "encrypted_model_checkpoint.pkl"  # used to store encrypted checkpoints in aggreg_fit_checkpoint (as path_checkpoint)
n_qubits: 4
n_layers: 6
