name: Python Linting and Formatting

on:
  push:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check for changes in /src
        id: check_changes
        run: echo "::set-output name=changes::$(git diff --name-only ${{ github.sha }}...HEAD src)"

      - name: Install dependencies
        if: steps.check_changes.outputs.changes != ''
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install pipenv
          pipenv install --dev

      - name: Run black
        if: steps.check_changes.outputs.changes != ''
        run: pipenv run black src --check --diff

      - name: Run pylint
        if: steps.check_changes.outputs.changes != ''
        run: pipenv run pylint src